version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.22
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

